version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - APP_PORT=3000
      - REDIS_URI=redis://redis:6379
      - REDIS_PREFIX=mcp-client
      - MCP_SERVER_SCRIPT_PATH=./src/server/dist/index.js
      - BACKEND_URL=${BACKEND_URL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: